"""Core modules for Beyond Ralph.

This package contains the core infrastructure:
- Orchestrator: Main control loop
- Session Manager: Claude Code session spawning
- Quota Manager: Usage limit monitoring
- Knowledge Base: Shared knowledge storage
- Records: Task tracking system
- Principles: Core integrity rules (NEVER FAKE RESULTS)

CORE PRINCIPLES (enforced throughout the system):
- NEVER fake results - unknown = blocked, failure = failure
- NEVER silent fallbacks - all fallbacks must be explicit and logged
- NEVER hide errors - report honestly, fail loudly
- NEVER skip verification - if it can be verified, verify it
- NEVER generate dishonest code - apps built must follow same rules

These principles apply to ALL agents and ALL code generated by Beyond Ralph.
"""

from beyond_ralph.core.knowledge import (
    KnowledgeBase,
    KnowledgeEntry,
    create_knowledge_entry,
)
from beyond_ralph.core.notifications import (
    NotificationChannel,
    NotificationLevel,
    NotificationManager,
    get_notification_manager,
)
from beyond_ralph.core.orchestrator import (
    Orchestrator,
    OrchestratorState,
    Phase,
    PhaseResult,
    ProjectStatus,
    get_orchestrator,
)
from beyond_ralph.core.principles import (
    AGENT_PRINCIPLES_PROMPT,
    CODE_REVIEW_PRINCIPLES_CHECKLIST,
    CORE_PRINCIPLES,
    PRINCIPLES_SUMMARY,
    get_code_review_checklist,
    get_full_principles,
    get_principles_for_prompt,
    get_principles_summary,
)
from beyond_ralph.core.quota_manager import (
    QuotaManager,
    QuotaStatus,
    check_quota,
    get_quota_manager,
)
from beyond_ralph.core.records import (
    Checkbox,
    RecordsManager,
    Task,
)
from beyond_ralph.core.session_manager import (
    SessionInfo,
    SessionManager,
    SessionStatus,
    get_session_manager,
)
from beyond_ralph.core.dynamic_plan import (
    DynamicPlanManager,
    Discrepancy,
    ModuleRequirement,
    RequirementPriority,
    RequirementStatus,
    get_dynamic_plan_manager,
)
from beyond_ralph.core.review_loop import (
    ReviewCycle,
    ReviewItem,
    ReviewItemCategory,
    ReviewItemSeverity,
    ReviewItemStatus,
    ReviewLoopManager,
    get_review_loop_manager,
)
from beyond_ralph.core.user_interaction import (
    InteractionStatus,
    InteractionType,
    ProgressUpdate,
    QuestionOption,
    UserInteraction,
    UserInteractionManager,
    get_user_interaction_manager,
)
from beyond_ralph.core.api_docs import (
    APIDocIngester,
    APIDocType,
    APIDocumentation,
    APIEndpoint,
    APISchema,
    get_api_doc_ingester,
)

__all__ = [
    # Orchestrator
    "Orchestrator",
    "OrchestratorState",
    "Phase",
    "PhaseResult",
    "ProjectStatus",
    "get_orchestrator",
    # Notifications
    "NotificationChannel",
    "NotificationLevel",
    "NotificationManager",
    "get_notification_manager",
    # Knowledge Base
    "KnowledgeBase",
    "KnowledgeEntry",
    "create_knowledge_entry",
    # Quota Manager
    "QuotaManager",
    "QuotaStatus",
    "check_quota",
    "get_quota_manager",
    # Records
    "Checkbox",
    "RecordsManager",
    "Task",
    # Session Manager
    "SessionInfo",
    "SessionManager",
    "SessionStatus",
    "get_session_manager",
    # Principles (CRITICAL - enforced everywhere)
    "CORE_PRINCIPLES",
    "PRINCIPLES_SUMMARY",
    "AGENT_PRINCIPLES_PROMPT",
    "CODE_REVIEW_PRINCIPLES_CHECKLIST",
    "get_principles_for_prompt",
    "get_full_principles",
    "get_principles_summary",
    "get_code_review_checklist",
    # Dynamic Plan (CRITICAL - inter-module requirements)
    "DynamicPlanManager",
    "Discrepancy",
    "ModuleRequirement",
    "RequirementPriority",
    "RequirementStatus",
    "get_dynamic_plan_manager",
    # Review Loop (MANDATORY - coding agent must fix ALL items)
    "ReviewCycle",
    "ReviewItem",
    "ReviewItemCategory",
    "ReviewItemSeverity",
    "ReviewItemStatus",
    "ReviewLoopManager",
    "get_review_loop_manager",
    # User Interaction (routing AskUserQuestion from subagents)
    "InteractionStatus",
    "InteractionType",
    "ProgressUpdate",
    "QuestionOption",
    "UserInteraction",
    "UserInteractionManager",
    "get_user_interaction_manager",
    # API Documentation Ingestion
    "APIDocIngester",
    "APIDocType",
    "APIDocumentation",
    "APIEndpoint",
    "APISchema",
    "get_api_doc_ingester",
]
