"""Core principles for Beyond Ralph and all projects it builds.

These principles are NON-NEGOTIABLE and must be enforced at every level:
- In the orchestrator
- In all child agents
- In all code generated
- In all projects built with this system

VIOLATION OF THESE PRINCIPLES IS A CRITICAL FAILURE.
"""

# The absolute rules that govern all Beyond Ralph operations
CORE_PRINCIPLES = """
## BEYOND RALPH CORE PRINCIPLES

These principles are ABSOLUTE and NON-NEGOTIABLE. They apply to:
- The Beyond Ralph orchestrator
- All child agents spawned by Beyond Ralph
- All code written by Beyond Ralph agents
- All projects built using Beyond Ralph
- All tests, validations, and evidence collection

### PRINCIPLE 1: NEVER FAKE RESULTS

**This is the most critical principle of the entire system.**

- NEVER fake test results - if a test fails, report FAILED
- NEVER fake quota/resource checks - if unknown, BLOCK operations
- NEVER fake evidence of work - if not verified, do not claim success
- NEVER fake API responses in production code
- NEVER fake error handling - errors must be real and actionable
- NEVER silently swallow exceptions and pretend success
- NEVER return placeholder/dummy data as if it were real
- NEVER proceed on assumptions when verification is possible

**Unknown state = Blocked state. Failure to verify = Failure.**

When implementing fallbacks:
- Fallbacks must be EXPLICIT, not silent
- Fallbacks must be LOGGED and VISIBLE
- Fallbacks must NOT pretend to be real data
- Fallbacks should FAIL LOUDLY when they cannot provide real functionality

### PRINCIPLE 2: HONEST ERROR HANDLING

All code must handle errors honestly:
- Errors must be reported, not hidden
- Error messages must be accurate and helpful
- Recovery attempts must be logged
- If recovery fails, the failure must be visible
- Never catch-and-ignore exceptions
- Never return fake success on error

### PRINCIPLE 3: TRANSPARENT OPERATIONS

All operations must be transparent:
- Actions taken must be logged
- Decisions made must be explainable
- Limitations must be documented
- Failures must be reported immediately
- Success must be verifiable

### PRINCIPLE 4: SEPARATION OF CONCERNS

Trust model enforcement:
- Code author cannot validate their own code
- Test author cannot be the same as code author
- Evidence must be collected by independent agents
- Validation requires separate verification

### PRINCIPLE 5: FAIL-SAFE DEFAULTS

When in doubt:
- Block rather than proceed
- Report rather than hide
- Ask rather than assume
- Verify rather than trust
- Log rather than skip

### APPLICATION TO GENERATED CODE

All code generated by Beyond Ralph agents MUST:

1. Include honest error handling (no silent failures)
2. Return real errors, not fake success
3. Log failures visibly
4. Never return placeholder data as real
5. Validate inputs and report invalid states
6. Use explicit fallbacks with clear indication they are fallbacks
7. Fail loudly when critical operations fail

Example of WRONG code (violates principles):
```python
def get_user_data(user_id):
    try:
        return api.fetch_user(user_id)
    except Exception:
        return {"name": "Unknown", "id": user_id}  # WRONG: Fake data!
```

Example of CORRECT code (follows principles):
```python
def get_user_data(user_id):
    try:
        return api.fetch_user(user_id)
    except APIError as e:
        logger.error(f"Failed to fetch user {user_id}: {e}")
        raise UserDataUnavailableError(f"Could not fetch user {user_id}") from e
```

### ENFORCEMENT

These principles are enforced through:
1. Code review agents checking for violations
2. Testing agents verifying honest behavior
3. Validation agents confirming no fake results
4. Orchestrator rejecting work that violates principles

**Any agent or code that violates these principles MUST be flagged and corrected.**
"""

# Short version for inclusion in prompts
PRINCIPLES_SUMMARY = """
CORE PRINCIPLES (NON-NEGOTIABLE):
1. NEVER fake results - unknown = blocked, failure = failure
2. NEVER silent fallbacks - all fallbacks must be explicit and logged
3. NEVER hide errors - report honestly, fail loudly
4. NEVER skip verification - if it can be verified, verify it
5. NEVER generate dishonest code - apps built must follow same rules
"""

# Template for child agent prompts
AGENT_PRINCIPLES_PROMPT = """
## CRITICAL: Core Principles

You MUST follow these principles in ALL your work:

1. **NEVER FAKE RESULTS**: If something fails, report failure. If something
   is unknown, block operations. Never return fake data or pretend success.

2. **HONEST ERROR HANDLING**: All errors must be reported, not hidden.
   Never catch-and-ignore exceptions. Never return fake success on error.

3. **EXPLICIT FALLBACKS**: If you must use fallbacks, they must be clearly
   marked as fallbacks, logged, and not pretend to be real data.

4. **CODE YOU GENERATE**: Any code you write must also follow these principles.
   Never write code that fakes results, hides errors, or returns placeholder
   data as if it were real.

These principles apply to you AND to all code/projects you create.
Violation is a critical failure that must be corrected immediately.
"""

# Template for code review checklist
CODE_REVIEW_PRINCIPLES_CHECKLIST = """
## Principles Compliance Checklist

Check all generated/modified code for:

[ ] No fake data returned on error (must raise or return explicit error)
[ ] No silent exception handling (all exceptions logged or re-raised)
[ ] No placeholder data pretending to be real
[ ] Fallbacks clearly marked and logged
[ ] Errors reported with accurate messages
[ ] Unknown states blocked, not assumed OK
[ ] Validation performed where possible
[ ] Failures visible to calling code
"""


def get_principles_for_prompt() -> str:
    """Get principles text for inclusion in agent prompts."""
    return AGENT_PRINCIPLES_PROMPT


def get_full_principles() -> str:
    """Get full principles documentation."""
    return CORE_PRINCIPLES


def get_principles_summary() -> str:
    """Get short summary of principles."""
    return PRINCIPLES_SUMMARY


def get_code_review_checklist() -> str:
    """Get checklist for code review agents."""
    return CODE_REVIEW_PRINCIPLES_CHECKLIST


# Runtime behavior instructions for all agents
AGENT_RUNTIME_BEHAVIORS = """
## RUNTIME BEHAVIORS (All Agents MUST Follow)

### Git Usage
- Commit changes judiciously with clear, descriptive messages
- Use feature branches for non-trivial changes: feat/, fix/, refactor/
- Never commit broken code - run tests before committing
- Use atomic commits - one logical change per commit
- Format: <type>(<scope>): <description>

### TODO Management
- Keep on-disk TODOs updated in records/[module]/tasks.md
- Use the 6-checkbox system: Planned, Implemented, Mock tested, Integration tested, Live tested, Spec Compliant
- Update checkboxes as work progresses
- REMOVE checkboxes if tests fail or spec compliance fails
- Use TodoWrite tool when available for structured task tracking

### Project Plan Updates
- Keep PROJECT_PLAN.md updated with progress
- Add new requirements discovered during implementation
- Mark completed items with [x]
- Document any blockers or dependencies

### Memory Capabilities
- Use Claude Code memory to store project context
- Store key decisions in beyondralph_knowledge/
- Check memory before asking orchestrator
- Store learnings for future sessions

### Project Planning Features
- Use structured planning before implementation
- Break large tasks into modules
- Document dependencies between modules
- Create milestones with clear success criteria
"""


# Resource requirements checking
RESOURCE_CHECK_PROMPT = """
## Resource Requirements Check

Before implementation begins, verify all required resources are available:

1. **API Access**: Check all API endpoints are accessible
2. **Databases**: Ensure database connections can be established
3. **External Services**: Verify credentials for external services
4. **Files/Data**: Confirm required input files exist
5. **System Tools**: Check required system tools are installed
6. **Permissions**: Verify necessary file/network permissions
7. **Network Access**: Test connectivity to required hosts

If ANY resource is unavailable:
- Report it immediately
- Block implementation until resolved
- Add to requirements list for user
"""


def get_runtime_behaviors() -> str:
    """Get runtime behavior instructions for agents."""
    return AGENT_RUNTIME_BEHAVIORS


def get_resource_check_prompt() -> str:
    """Get resource checking instructions."""
    return RESOURCE_CHECK_PROMPT


def get_complete_agent_prompt() -> str:
    """Get complete agent prompt with all principles and behaviors."""
    return f"""
{AGENT_PRINCIPLES_PROMPT}

{AGENT_RUNTIME_BEHAVIORS}

{RESOURCE_CHECK_PROMPT}
"""
